name: AISOC Internship Workspace
description: Use this template to submit a project proposal for the AISOC internship program.
title: "AISOC Workspace: <Project Title>"
labels: ["aisoc", "proposal"]
assignees: []

body:
  - type: input
    id: project_title
    attributes:
      label: 🧠 Project Title
      description: Briefly describe the title of your project
      placeholder: Acoustic Source and Event Detection DCASE Challenge-Inspired Smart App 
    validations:
      required: true

  - type: textarea
    id: team_details
    attributes:
      label: 👥 Team Details
      description: Provide the team name, member names, and email addresses
      placeholder: |
        - Team Name: Audible Intelligence
        - Member 1: Ojas Arora (ojas.arora14@email.com)
        - Member 2: Diksha (diksha160404@email.com)
        - Member 3: Chitwan (chitwan.gujrani@email.com)
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: 🧩 Problem Statement
      description: Briefly describe the problem your project aims to solve
      placeholder: Traditional acoustic event detection software relies significantly on cloud processing, which results in privacy threats, latency, and poor offline performance. An urgent need exists for an end-to-end, privacy-centered solution that can detect alarms, sirens, or barks accurately in real-time directly on-device—providing low latency, improved security, and smooth performance in low-resource or offline settings.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 🚀 Motivation
      description: Explain the motivation or background behind choosing this project
      placeholder: The rising demand for smart, context-aware environments inspired us to build a solution that ensures safety and accessibility through sound. Motivated by the DCASE Challenge, we aim to create a real-time, privacy-focused acoustic detection system that works even in low-resource or offline settings—bridging the gap between AI innovation and real-world usability.
    validations:
      required: true

  - type: textarea
    id: expected_outcome
    attributes:
      label: 🎯 Expected Outcome
      description: List the expected outcomes from the project as bullet points
      placeholder: |
        - Real-time acoustic event detection app (mobile/web)
        - User-friendly interface for sound alerts and feedback
        - Optional dashboard for event monitoring/logging
        - Complete documentation and deployment guide
    validations:
      required: true

  - type: textarea
    id: timeline
    attributes:
      label: 📅 Timeline & Milestones
      description: Provide a timeline with measurable milestones (e.g. weekly)
      placeholder: |
        - Week 1–2: Requirement gathering and architecture design
        - Week 3–4: Initial development and testing
        - Week 5–6: Feature finalization and integration
        - Week 7–8: Final testing and documentation
    validations:
      required: true

  - type: textarea
    id: deliverables
    attributes:
      label: 📦 Final Deliverables
      description: Describe the expected final deliverables at the end of the program
      placeholder: |
        - Fully functional mobile/web app for acoustic event detection
        - Source code with clean documentation and setup guide
        - Final presentation showcasing the solution and roadmap
        - Publicly hosted demo link
    validations:
      required: true

  - type: textarea
    id: appendix
    attributes:
      label: 📎 Appendix (Optional)
      description: Add any extra information, links, or references
      placeholder: |
        - GitHub repository link
        - Reference documents or datasets
        - Related prior work
    validations:
      required: false
